language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  # - "3.8"
  - "nightly"  # nightly build
jobs:
  include:
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'